server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/clean_db?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.hyungseok.cleanarchitecture.domain.model